### ISSUE TITLE
TypeError with certain strings

### ISSUE THREAD

**Issue by rdagger** [i-infra/uQR#1]
I'm getting a TypeError with the following code:

```
from uQR import QRCode
qr = QRCode()
qr.add_data('WIFI')
matrix = qr.get_matrix()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uQR.py", line 1297, in get_matrix
  File "uQR.py", line 1053, in make
  File "uQR.py", line 1124, in best_fit
  File "uQR.py", line 818, in write
TypeError: can't convert 'int' object to str implicitly
```
I'm running MicroPython v1.19.1 on 2022-08-02; Raspberry Pi Pico W with RP2040

**Comment by ghost** [comment]
Literally having the exact same issue 3 years later.

**Comment by rdagger** [comment]
> Literally having the exact same issue 3 years later.

I don't recall how I fixed it or if I had to modify uQR.py but I did get it working.  Check out [demo_qr.py](https://github.com/rdagger/micropython-ssd1322/blob/master/demo_qr.py) in my repo: https://github.com/rdagger/micropython-ssd1322

**Comment by ghost** [comment]
Thanks for that, just figured out a solution though.
I managed to fix it by adapting the write function on line 800~

```py
    def write(self, buffer):
        if self.mode == MODE_NUMBER:
            for i in range(0, len(self.data), 3):
                chars = self.data[i : i + 3]
                bit_length = NUMBER_LENGTH[len(chars)]
                # Fix: decode bytes to string before converting to int
                if isinstance(chars, bytes):
                    chars = chars.decode('utf-8')
                buffer.put(int(chars), bit_length)
        elif self.mode == MODE_ALPHA_NUM:
            for i in range(0, len(self.data), 2):
                chars = self.data[i : i + 2]
                if len(chars) > 1:
                    # Fix: when indexing bytes, wrap in bytes() to keep as bytes for find()
                    buffer.put(
                        ALPHA_NUM.find(bytes([chars[0]])) * 45 + ALPHA_NUM.find(bytes([chars[1]])), 11
                    )
                else:
                    # Fix: when indexing bytes, wrap in bytes() to keep as bytes for find()
                    buffer.put(ALPHA_NUM.find(bytes([chars[0]])), 6)
        else:
            data = self.data
            for c in data:
                buffer.put(c, 8)
```
